In [1]:
import numpy as np
import torch

In [6]:
#LISTS
list1 = [1, 5, 6, 10]
list1


[1, 5, 6, 10]

In [7]:
list2 = [[4, 6, 7, 10], [10, 14, 20, 25]]
list2

[[4, 6, 7, 10], [10, 14, 20, 25]]

In [9]:
#Numpy Arrays
np1 = np.random.rand(4, 2)
np1

array([[0.72678097, 0.67359074],
       [0.67730669, 0.37141279],
       [0.77623393, 0.45783638],
       [0.56180413, 0.18517525]])

In [15]:
#Tensors
tensor1 = torch.randn(2, 3)
tensor1
# tensor1.dtype = torch.float32

tensor([[-0.4888,  0.6811,  0.2867],
        [ 2.7276, -0.2542,  0.7101]])

In [12]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
#Creating tensors out of Numpy Arrays
my_tensors = torch.tensor(np1)
my_tensors

tensor([[0.7268, 0.6736],
        [0.6773, 0.3714],
        [0.7762, 0.4578],
        [0.5618, 0.1852]], dtype=torch.float64)