In [1]:
import torch

In [2]:
my_tensor = torch.arange(15)
my_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
#Reshape and View: It helps us reshape the data.
my_tensor = my_tensor.reshape(3, 5)
my_tensor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [4]:
#Reshaping when we don't know the items.
# -1 helps us determine it during this case.
my_tensor2 = torch.arange(15)
my_tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
my_tensor2 = my_tensor.reshape(3, -1)
my_tensor2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [6]:
#View
my_tensor3 = torch.arange(15)
my_tensor3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
my_tensor3 = my_tensor3.view(3, 5)
my_tensor3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [8]:
#Reshape and View will update automatically.
my_tensor4 = torch.arange(10)
my_tensor4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_tensor5 = my_tensor4.reshape(2, 5)
my_tensor5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_tensor4[2] = 45
my_tensor4

tensor([ 0,  1, 45,  3,  4,  5,  6,  7,  8,  9])

In [11]:
my_tensor5

tensor([[ 0,  1, 45,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [12]:
#Slices
my_tensor6 = torch.arange(10)
my_tensor6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_tensor6[5]

tensor(5)

In [14]:
#Grabbing a slice
my_tensor7 = torch.arange(15)
my_tensor7

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
my_tensor7 = my_tensor7.reshape(5, 3)
my_tensor7

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [16]:
my_tensor7[:, 1]

tensor([ 1,  4,  7, 10, 13])

In [17]:
#Returning the column(s)
my_tensor7[:, 1:2]

tensor([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]])

**Tensor Math Operations**

In [18]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [19]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [20]:
#Addition Function
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [22]:
#Subtraction Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [23]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [24]:
#Multiplication Function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [25]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [26]:
#Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [28]:
#Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [29]:
#Remainder Function
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [30]:
#Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [32]:
#Reassignment
#tensor_a = tensor_a + tensor_b #Option 1#

tensor_a.add_(tensor_b)   #Option 2
tensor_a

tensor([ 6,  8, 10, 12])